import { describe, it, expect } from 'vitest';
import {
  WsDrawSchema,
  WsDrawDeltaSchema,
  WsCommitSchema,
  WsBranchUpdateSchema,
  WsCursorSchema,
  WsProfileSchema,
  WsPingSchema,
  WsPongSchema,
  WsFollowRequestSchema,
  WsFollowAcceptSchema,
  WsFollowStopSchema,
  WsFullsyncRequestSchema,
  WsObjectLockSchema,
  WsObjectUnlockSchema,
  InboundWsMessageSchema,
  WsViewSyncSchema,
  MAX_WS_PAYLOAD_BYTES,
} from './wsSchemas';

describe('WsDrawSchema', () => {
  it('accepts valid draw message', () => {
    expect(WsDrawSchema.safeParse({ type: 'draw', canvas: '{}' }).success).toBe(true);
  });

  it('rejects missing canvas', () => {
    expect(WsDrawSchema.safeParse({ type: 'draw' }).success).toBe(false);
  });

  it('rejects canvas that is too short', () => {
    expect(WsDrawSchema.safeParse({ type: 'draw', canvas: '{' }).success).toBe(false);
  });
});

describe('WsDrawDeltaSchema', () => {
  it('accepts valid draw-delta message', () => {
    const msg = { type: 'draw-delta', added: [], modified: [], removed: [] };
    expect(WsDrawDeltaSchema.safeParse(msg).success).toBe(true);
  });

  it('rejects when added exceeds 500 items', () => {
    const msg = { type: 'draw-delta', added: Array(501).fill({}), modified: [], removed: [] };
    expect(WsDrawDeltaSchema.safeParse(msg).success).toBe(false);
  });
});

describe('WsCommitSchema', () => {
  const valid = {
    type: 'commit',
    sha: 'abc12345',
    commit: {
      branch: 'main',
      message: 'Initial commit',
      canvas: '{}',
    },
  };

  it('accepts valid commit', () => {
    expect(WsCommitSchema.safeParse(valid).success).toBe(true);
  });

  it('rejects sha that is too short', () => {
    expect(WsCommitSchema.safeParse({ ...valid, sha: 'short' }).success).toBe(false);
  });

  it('accepts empty message (auto-generated by client)', () => {
    expect(WsCommitSchema.safeParse({ ...valid, commit: { ...valid.commit, message: '' } }).success).toBe(true);
  });

  it('rejects empty branch', () => {
    expect(WsCommitSchema.safeParse({ ...valid, commit: { ...valid.commit, branch: '' } }).success).toBe(false);
  });

  it('accepts optional isMerge field', () => {
    expect(WsCommitSchema.safeParse({ ...valid, commit: { ...valid.commit, isMerge: true } }).success).toBe(true);
  });

  it('accepts optional parents array', () => {
    expect(WsCommitSchema.safeParse({ ...valid, commit: { ...valid.commit, parents: ['abc12345', 'def67890'] } }).success).toBe(true);
  });
});

describe('WsCursorSchema', () => {
  it('accepts valid cursor', () => {
    expect(WsCursorSchema.safeParse({ type: 'cursor', x: 100, y: 200 }).success).toBe(true);
  });

  it('rejects non-finite numbers', () => {
    expect(WsCursorSchema.safeParse({ type: 'cursor', x: Infinity, y: 0 }).success).toBe(false);
  });

  it('rejects missing coordinates', () => {
    expect(WsCursorSchema.safeParse({ type: 'cursor' }).success).toBe(false);
  });
});

describe('WsProfileSchema', () => {
  it('accepts profile with name and color', () => {
    expect(WsProfileSchema.safeParse({ type: 'profile', name: 'Alice', color: '#ff0000' }).success).toBe(true);
  });

  it('accepts profile with no fields', () => {
    expect(WsProfileSchema.safeParse({ type: 'profile' }).success).toBe(true);
  });
});

describe('WsPingSchema / WsPongSchema', () => {
  it('accepts ping', () => {
    expect(WsPingSchema.safeParse({ type: 'ping' }).success).toBe(true);
  });

  it('accepts pong', () => {
    expect(WsPongSchema.safeParse({ type: 'pong' }).success).toBe(true);
  });
});

describe('WsViewSyncSchema', () => {
  it('accepts valid view-sync message with only required fields', () => {
    const msg = { type: 'view-sync', vpt: [1, 0, 0, 1, 0, 0] };
    expect(WsViewSyncSchema.safeParse(msg).success).toBe(true);
  });

  it('accepts valid view-sync message with all fields', () => {
    const msg = { type: 'view-sync', vpt: [1, 0, 0, 1, 0, 0], branch: 'main', headSha: 'abc12345' };
    expect(WsViewSyncSchema.safeParse(msg).success).toBe(true);
  });

  it('rejects missing vpt', () => {
    const msg = { type: 'view-sync' };
    expect(WsViewSyncSchema.safeParse(msg).success).toBe(false);
  });

  it('rejects vpt with incorrect number of elements', () => {
    const msg = { type: 'view-sync', vpt: [1, 0, 0, 1, 0] };
    expect(WsViewSyncSchema.safeParse(msg).success).toBe(false);

    const msg2 = { type: 'view-sync', vpt: [1, 0, 0, 1, 0, 0, 0] };
    expect(WsViewSyncSchema.safeParse(msg2).success).toBe(false);
  });

  it('rejects vpt with non-finite numbers', () => {
    const msg = { type: 'view-sync', vpt: [1, 0, 0, Infinity, 0, 0] };
    expect(WsViewSyncSchema.safeParse(msg).success).toBe(false);
  });

  it('rejects branch exceeding maximum length', () => {
    const branch = 'a'.repeat(101);
    const msg = { type: 'view-sync', vpt: [1, 0, 0, 1, 0, 0], branch };
    expect(WsViewSyncSchema.safeParse(msg).success).toBe(false);
  });

  it('rejects headSha exceeding maximum length', () => {
    const headSha = 'a'.repeat(65);
    const msg = { type: 'view-sync', vpt: [1, 0, 0, 1, 0, 0], headSha };
    expect(WsViewSyncSchema.safeParse(msg).success).toBe(false);
  });
});

describe('WsBranchUpdateSchema', () => {
  it('accepts valid branch-update message', () => {
    expect(WsBranchUpdateSchema.safeParse({ type: 'branch-update', branch: 'main', headSha: 'abc12345' }).success).toBe(true);
  });

  it('rejects missing headSha', () => {
    expect(WsBranchUpdateSchema.safeParse({ type: 'branch-update', branch: 'main' }).success).toBe(false);
  });

  it('rejects empty branch', () => {
    expect(WsBranchUpdateSchema.safeParse({ type: 'branch-update', branch: '', headSha: 'abc12345' }).success).toBe(false);
  });
});

describe('WsFollowRequestSchema', () => {
  it('accepts valid follow-request message', () => {
    expect(WsFollowRequestSchema.safeParse({ type: 'follow-request' }).success).toBe(true);
  });

  it('rejects invalid message', () => {
    expect(WsFollowRequestSchema.safeParse({ type: 'other' }).success).toBe(false);
  });
});

describe('WsFollowAcceptSchema', () => {
  it('accepts valid follow-accept message', () => {
    expect(WsFollowAcceptSchema.safeParse({ type: 'follow-accept' }).success).toBe(true);
  });

  it('rejects invalid message', () => {
    expect(WsFollowAcceptSchema.safeParse({ type: 'other' }).success).toBe(false);
  });
});

describe('WsFollowStopSchema', () => {
  it('accepts valid follow-stop message', () => {
    expect(WsFollowStopSchema.safeParse({ type: 'follow-stop' }).success).toBe(true);
  });

  it('rejects invalid message', () => {
    expect(WsFollowStopSchema.safeParse({ type: 'other' }).success).toBe(false);
  });
});

describe('WsFullsyncRequestSchema', () => {
  it('accepts valid fullsync-request message without senderId', () => {
    expect(WsFullsyncRequestSchema.safeParse({ type: 'fullsync-request' }).success).toBe(true);
  });

  it('accepts valid fullsync-request message with senderId', () => {
    expect(WsFullsyncRequestSchema.safeParse({ type: 'fullsync-request', senderId: 'abc12345' }).success).toBe(true);
  });

  it('rejects fullsync-request when senderId exceeds 64 characters', () => {
    const longSenderId = 'a'.repeat(65);
    expect(WsFullsyncRequestSchema.safeParse({ type: 'fullsync-request', senderId: longSenderId }).success).toBe(false);
  });

  it('rejects fullsync-request with invalid type', () => {
    expect(WsFullsyncRequestSchema.safeParse({ type: 'invalid-request' }).success).toBe(false);
  });
});

describe('WsObjectLockSchema / WsObjectUnlockSchema', () => {
  it('accepts valid object-lock message', () => {
    expect(
      WsObjectLockSchema.safeParse({ type: 'object-lock', objectIds: ['obj1', 'obj2'] }).success
    ).toBe(true);
  });

  it('accepts valid object-lock message with color', () => {
    expect(
      WsObjectLockSchema.safeParse({ type: 'object-lock', objectIds: ['obj1'], color: '#00ff00' }).success
    ).toBe(true);
  });

  it('rejects object-lock with missing objectIds', () => {
    expect(WsObjectLockSchema.safeParse({ type: 'object-lock' }).success).toBe(false);
  });

  it('rejects object-lock with too many objectIds', () => {
    const objectIds = Array.from({ length: 501 }, (_, i) => `obj${i}`);
    expect(WsObjectLockSchema.safeParse({ type: 'object-lock', objectIds }).success).toBe(false);
  });

  it('accepts valid object-unlock message', () => {
    expect(WsObjectUnlockSchema.safeParse({ type: 'object-unlock' }).success).toBe(true);
  });
});

describe('InboundWsMessageSchema discriminated union', () => {
  it('dispatches to correct schema by type', () => {
    const result = InboundWsMessageSchema.safeParse({ type: 'ping' });
    expect(result.success).toBe(true);
    if (result.success) expect(result.data.type).toBe('ping');
  });

  it('accepts branch-update messages', () => {
    const result = InboundWsMessageSchema.safeParse({ type: 'branch-update', branch: 'main', headSha: 'abc12345' });
    expect(result.success).toBe(true);
  });

  it('accepts fullsync-request messages', () => {
    const result = InboundWsMessageSchema.safeParse({ type: 'fullsync-request' });
    expect(result.success).toBe(true);
  });

  it('rejects unknown type', () => {
    expect(InboundWsMessageSchema.safeParse({ type: 'unknown-type' }).success).toBe(false);
  });

  it('rejects missing type', () => {
    expect(InboundWsMessageSchema.safeParse({ canvas: '{}' }).success).toBe(false);
  });

  it('rejects commit missing required fields', () => {
    expect(InboundWsMessageSchema.safeParse({ type: 'commit', sha: 'abc12345' }).success).toBe(false);
  });
});

describe('MAX_WS_PAYLOAD_BYTES', () => {
  it('is exactly 512 KB', () => {
    expect(MAX_WS_PAYLOAD_BYTES).toBe(512 * 1024);
  });
});
